#!/bin/sh


python ~/github/Plotting/plotTwoColumnInputFiles.py '6 card Leduc' 'nodes touched' 'regret' ~/Dropbox/christian-tuomas-shared/mirror_prox/figures/3card_deterministic.pdf ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_cfr_walk_clean/output3card_leduc_preshuffled--solver\=cfr_walk--num_iterations\=10000000--output_iterations\=10--file_output\=1.txt 'CFR' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_egt_clean/output3card_leduc_preshuffled--solver\=egt--num_iterations\=1000000--output_iterations\=10--file_output\=1--egt_initial_mu\=1.5--prox_function\=weighted.txt 'EGT' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_smp_deterministic_clean/output3card_leduc_preshuffled--solver\=smp--num_iterations\=1000000--output_iterations\=10--file_output\=1--prox_function\=weighted--smp_alpha\=0.283--smp_kappa\=1000000.txt 'MP'


python ~/github/Plotting/plotTwoColumnInputFiles.py '10 card Leduc' 'nodes touched' 'regret' ~/Dropbox/christian-tuomas-shared/mirror_prox/figures/5card_deterministic.pdf ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_cfr_walk_clean/output5card_leduc_preshuffled--solver\=cfr_walk--num_iterations\=1000000--output_iterations\=10--file_output\=1.txt 'CFR' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_egt_clean/output5card_leduc_preshuffled--solver\=egt--num_iterations\=1000000--output_iterations\=10--file_output\=1--egt_initial_mu\=1.5--prox_function\=weighted.txt 'EGT' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_smp_deterministic_clean/output5card_leduc_preshuffled--solver\=smp--num_iterations\=1000000--output_iterations\=10--file_output\=1--smp_alpha\=0.86538--smp_kappa\=1000000.txt 'MP'




python ~/github/Plotting/plotTwoColumnInputFiles.py '16 card Leduc' 'nodes touched' 'regret' ~/Dropbox/christian-tuomas-shared/mirror_prox/figures/8card_deterministic.pdf ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_cfr_walk_clean/output8card_leduc_preshuffled--solver\=cfr_walk--num_iterations\=1000000--output_iterations\=10--file_output\=1.txt 'CFR' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_egt_clean/output8card_leduc_preshuffled--solver\=egt--num_iterations\=1000000--output_iterations\=10--file_output\=1--egt_initial_mu\=2--prox_function\=weighted.txt 'EGT' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_smp_deterministic_clean/output8card_leduc_preshuffled--solver\=smp--num_iterations\=1000000--output_iterations\=10--file_output\=1--prox_function=weighted--smp_alpha\=0.5--smp_kappa\=1000000.txt 'MP'





python ~/github/Plotting/plotTwoColumnInputFiles.py '30 card Leduc' 'nodes touched' 'regret' ~/Dropbox/christian-tuomas-shared/mirror_prox/figures/15card_deterministic.pdf ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_cfr_walk_clean/output15card_leduc_preshuffled--solver\=cfr_walk--num_iterations\=1000000--output_iterations\=10--file_output\=1.txt 'CFR' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_egt_clean/output15card_leduc_preshuffled--solver\=egt--num_iterations\=1000000--output_iterations\=10--file_output\=1--egt_initial_mu\=2--prox_function\=weighted.txt 'EGT' ~/Documents/research/equilibrium_computation/mirror_prox/bellagio_data/final_smp_deterministic_clean/output15card_leduc_preshuffled--solver\=smp--num_iterations\=1000000--output_iterations\=10--file_output\=1--prox_function=weighted--smp_alpha\=0.5--smp_kappa\=1000000.txt 'MP'
